[tool.poetry]
name = "aws-rag-bot"
version = "0.1.3"
description = ""
authors = ["danjamk <dan@risegardens.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
